version: '3.4'
services:
  ui:
    build:
      context: .
      target: base
    container_name: tweeter_ui
    image: tweeter_ui
    command: npm start
    ports:
      - '3000:3000'
    volumes:
      - .:/usr/src/app
      - /usr/src/app/node_modules

